---
name: mcvs-python-action
description: |
  The Mission Critical Vulnerability Scanner (MCVS) Python action.
inputs:
  pyinstaller-binary-name:
    description: The name of the binary that is created using pyinstaller.
  token:
    description: |
      A token is required to allow the mcvs-python-action to push the
      package that it has been built, to the packages repository of the GitHub
      repository where the action has been run.
    required: true
runs:
  using: composite
  steps:
    #
    # Install the python version that has been defined in the .python-version
    # file.
    #
    # yamllint disable-line rule:line-length
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        cache: pip
    #
    # Code security scanning.
    #
    # yamllint disable-line rule:line-length
    - uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v6.2.0
      with:
        only-fixed: false
        output-format: table
        path: .
        severity-cutoff: high
    #
    # If a requirements file exists in the project, then install the packages.
    #
    - name: Install PIP packages defined in requirements.txt
      shell: bash
      run: |
        requirements_file=requirements.txt
        if [ -f ${requirements_file} ]; then
          pip install \
            --requirement ${requirements_file}
        fi
    #
    # Run pytest if 'import pytest' is found.
    #
    - name: Run tests
      shell: bash
      run: |
        if grep -r 'import pytest' *.py; then
          pytest \
            --capture=no \
            --cov=main test.py \
            --cov-report term-missing \
            --verbose
        fi
    #
    # Lint code with Flake8
    #
    # yamllint disable rule:line-length
    - name: Code linting with Flake8
      shell: bash
      run: |
        python3 -m pip install \
          --require-hashes \
          --user \
          --requirement \
            ${GITHUB_ACTION_PATH}/configs/pip/flake8/requirements.txt

        errors=$(flake8 -v --max-line-length=150 --exclude=client/,.venv/,venv/ --count --statistics --exit-zero .)
        echo "Flake8 reported $errors errors/warnings."

        # Compare count to threshold, fail pipeline if above threshold
        if [ "$errors" -gt 4 ]; then
          echo "Too many issues — failing."
          exit 1
        else
          echo "Issues within acceptable range — passing."
        fi
    #
    # Build binary using pyinstaller and attach it to a release once a tag has
    # been created.
    #
    - name: Check Conditions
      id: condition_check
      run: echo "Checking conditions..."
      shell: bash
      if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') && inputs.pyinstaller-binary-name != '' }}
    # yamllint enable rule:line-length
    - name: Build binary using pyinstaller
      if: ${{ steps.condition_check.outcome == 'success' }}
      shell: bash
      run: |
        pip install pyinstaller==v6.13.0
        python3 -m pip install \
          --require-hashes \
          --user \
          --requirement \
            ${GITHUB_ACTION_PATH}/configs/pip/pyinstaller/requirements.txt
        pyinstaller --onefile main.py --name gomod-go-version-updater
    # yamllint disable-line rule:line-length
    - uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
      name: Attach a binary to a release
      if: ${{ steps.condition_check.outcome == 'success' }}
      with:
        repo_token: ${{ inputs.token }}
        file: dist/${{ inputs.pyinstaller-binary-name }}
        asset_name: ${{ inputs.pyinstaller-binary-name }}
        tag: ${{ github.ref }}
