---
name: MCVS-PR-validation-action
"on":
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
  workflow_call:
permissions:
  contents: read
  pull-requests: read
jobs:
  MCVS-PR-validation-action:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      # yamllint disable-line rule:line-length
      - uses: schubergphilis/mcvs-pr-validation-action@b1c337a896fea52b52a93335713a435d5a07ea72 # v0.2.0
